BasePath = 'D:\HMC_ComVeh_SCC_CUTIN\HMC_ComVeh_SCC_CUTIN';
DirList = dir(BasePath);
DirList = DirList([DirList.isdir]);

for iDir = 3:numel(DirList)
    aDir = fullfile(BasePath, DirList(iDir).name);
    fprintf('Processing: %s\n', aDir);
    cd(aDir)

    open('D:\HMC_ComVeh_SCC_CUTIN\Test_Battery_Ign_off.slx')
    sim('D:\HMC_ComVeh_SCC_CUTIN\Test_Battery_Ign_off.slx')
    close_system('D:\HMC_ComVeh_SCC_CUTIN\Test_Battery_Ign_off.slx')
    
    open('D:\HMC_ComVeh_SCC_CUTIN\Test_Battery_Ign_on.slx')
    sim('D:\HMC_ComVeh_SCC_CUTIN\Test_Battery_Ign_on.slx')
    close_system('D:\HMC_ComVeh_SCC_CUTIN\Test_Battery_Ign_on.slx')
           
    %% Set-up of variables
    Run(1).Settings ={};    
    ExeName = 'PreScan.CLI.exe';
    disp('Setting-up variables...');
    disp('------------------------');
    ExperimentName = 'SCC_CUTIN_01';
    MainExperiment = pwd;
    ExperimentDir = [pwd '\..'];
    ResultsDir = [MainExperiment '\Results\TA_' sprintf('%04.0f%02.0f%02.0f_%02.0f%02.0f%02.0f',clock)];
    
    % Number of simulations.
    NrOfRuns = length(Run);
    
   %% The simulations
    Results(NrOfRuns).Data = []; % Preallocate results structure.

    disp(['Scheduling ' num2str(NrOfRuns) ' simulations...']);
    disp('-------------------------');

    for i = 1:NrOfRuns
        disp(['Run: ' num2str(i) '/' num2str(NrOfRuns)]);
    
        RunName = ['Run_' num2str(i, '%03i')];
        RunModel = [RunName '_cs'];
        ResultDir = [ResultsDir '\' RunName];

        % Create the complete command
        Settings = cellstr('Altered Settings:');
        Command = ExeName;
        % Command = ExperimentName;
        Command = [Command ' -load ' '"' MainExperiment '"'];
        Command = [Command ' -save ' '"' ResultDir '"'];    
        for j=1:size(Run(i).Settings,1)
            tag = Run(i).Settings{j,1};
            val = num2str(Run(i).Settings{j,2}, '%50.50g');
            Command = [Command ' -set ' tag '=' val];
            Settings(end+1) = cellstr([tag ' = ' val]);
        end
        
        Command = [Command ' -build'];    
        Command = [Command ' -close'];
    
        % Execute the command (creates altered PreScan experiment).
        errorCode = dos(Command);
        if errorCode ~= 0
            disp(['Failed to perform command: ' Command]);
            continue;
        end

        % Navigate to new experiment.
        cd(ResultDir);
        open_system(RunModel);
    
        % Regenerate compilation sheet.
        regenButtonHandle = find_system(RunModel, 'FindAll', 'on', 'type', 'annotation','text','Regenerate');
        regenButtonCallbackText = get_param(regenButtonHandle,'ClickFcn');
        eval(regenButtonCallbackText);
    
        % Determine simulation start and end times (avoid infinite durations).
        activeConfig = getActiveConfigSet(RunModel);
        startTime = str2double(get_param(activeConfig, 'StartTime'));
        endTime = str2double(get_param(activeConfig, 'StopTime'));
    
        % Simulate the new model.
        sim(RunModel, [startTime endTime]);

    
        % Store current settings to file.
        fileID = fopen([ResultDir '\settings.txt'],'wt');
        for line=1:length(Settings)
            fprintf(fileID, '%s\n',char(Settings(line)));
        end
        fclose(fileID);
    
        % Store results to file.
        ResultFileDir = [ResultDir '\Results\'];
        [mkDirStatus,mkDirMessage,mkDirMessageid] = mkdir(ResultFileDir);

        save_system(RunModel);
        close_system(RunModel);
        
    end

%% DATA output
filename = 'output_data.xls';                                              

% DSA OUTPUT 
Time = output_data.time(:,1);
ACCDistanceAlertSignal = output_data.signals.values(:,1);
ACCMode = output_data.signals.values(:,2);
ACCSetDistanceMode = output_data.signals.values(:,3);
ACCSetSpeed = output_data.signals.values(:,4);
ACCSystemShutoffWarning = output_data.signals.values(:,5);
ACCTargetDetected = output_data.signals.values(:,6);
DistanceToForwardVehicle = output_data.signals.values(:,7);
ForwardCollisionWarning = output_data.signals.values(:,8);
RoadCurvature = output_data.signals.values(:,9);
SpeedOfForwardVehicle = output_data.signals.values(:,10);
SCC_OperatingStatus = output_data.signals.values(:,11);
LFA_HndsoffSnd = output_data.signals.values(:,12);
LFA_LHLnWrnSta = output_data.signals.values(:,13);
LFA_RcgSta = output_data.signals.values(:,14);
LFA_RHLnWrnSta = output_data.signals.values(:,15);
LFA_SymbolDisplay = output_data.signals.values(:,16);
LFA_SysWrn = output_data.signals.values(:,17);
ExtControlModeReq = output_data.signals.values(:,18);
FBFTorqueReq = output_data.signals.values(:,19);
MotorTorqueReq = output_data.signals.values(:,20);
SteeringAngleReq = output_data.signals.values(:,21);
ExtlAccelerationDemand = output_data.signals.values(:,22);
XBRCtrlMode = output_data.signals.values(:,23);
XBRPriority = output_data.signals.values(:,24);


Results_Names={'Time', ...
               'ACCDistanceAlertSignal', ...
               'ACCMode', ...
               'ACCSetDistanceMode', ...
               'ACCSetSpeed', ...
               'ACCSystemShutoffWarning', ...
               'ACCTargetDetected', ...
               'DistanceToForwardVehicle', ...
               'ForwardCollisionWarning', ...
               'RoadCurvature', ...
               'SpeedOfForwardVehicle', ...
               'SCC_OperatingStatus', ...
               'LFA_HndsoffSnd', ...
               'LFA_LHLnWrnSta', ...
               'LFA_RcgSta', ...
               'LFA_RHLnWrnSta', ...
               'LFA_SymbolDisplay', ...
               'LFA_SysWrn', ...
               'ExtControlModeReq', ...
               'FBFTorqueReq', ...
               'MotorTorqueReq', ...
               'SteeringAngleReq', ...
               'ExtlAccelerationDemand', ...
               'XBRCtrlMode', ...
               'XBRPriority'};
Results_Values=[Time, ...
                ACCDistanceAlertSignal, ...
                ACCMode, ...
                ACCSetDistanceMode, ...
                ACCSetSpeed, ...
                ACCSystemShutoffWarning, ...
                ACCTargetDetected, ...
                DistanceToForwardVehicle, ...
                ForwardCollisionWarning, ...
                RoadCurvature, ...
                SpeedOfForwardVehicle, ...
                SCC_OperatingStatus, ...
                LFA_HndsoffSnd, ...
                LFA_LHLnWrnSta, ...
                LFA_RcgSta, ...
                LFA_RHLnWrnSta, ...
                LFA_SymbolDisplay, ...
                LFA_SysWrn, ...
                ExtControlModeReq, ...
                FBFTorqueReq, ...
                MotorTorqueReq, ...
                SteeringAngleReq, ...
                ExtlAccelerationDemand, ...
                XBRCtrlMode, ...
                XBRPriority];

sheet=1;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=1;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);
    
% C-CAN 
Time = output_data.time(:,1);
ParkingBrakeSwitch = output_data.signals.values(:,25);
TransmissionNeutralSwitch = output_data.signals.values(:,26);
Door_LH_State =output_data.signals.values(:,27);
Door_RH_State = output_data.signals.values(:,28);
Seatbelt = output_data.signals.values(:,29);
C_AccDisSetSw = output_data.signals.values(:,30);
C_CcPtoEnableSW = output_data.signals.values(:,31);
C_CcRes_Dec_SW = output_data.signals.values(:,32);
C_CcSet_Inc_SW = output_data.signals.values(:,33);
C_LFA_Sw = output_data.signals.values(:,34);
C_Pause_Sw = output_data.signals.values(:,35);
BrakePedalPos = output_data.signals.values(:,36);
BrkPrssHghRngFrntLftWheel = output_data.signals.values(:,37);
BrkPrssHghRngFrntRghtWheel = output_data.signals.values(:,38);
BrkPrssHghRngRrLftWheel = output_data.signals.values(:,39);
BrkPrssHghRngRrRghtWheel = output_data.signals.values(:,40);
FrontAxleLeftWheelSpeed = output_data.signals.values(:,41);
FrontAxleRightWheelSpeed = output_data.signals.values(:,42);
RearAxleLeftWheelSpeed = output_data.signals.values(:,43);
RearAxleRightWheelSpeed = output_data.signals.values(:,44);
LateralAcceleration = output_data.signals.values(:,45);
LongitudinalAcceleration = output_data.signals.values(:,46);
SteerWheelAngle = output_data.signals.values(:,47);
YawRate = output_data.signals.values(:,48);
BrakeSwitch = output_data.signals.values(:,49);
MFSMmsg02_ParkingBrakeSwitch = output_data.signals.values(:,50);
SteeringAngle = output_data.signals.values(:,51);
SteeringAngleSpeed = output_data.signals.values(:,52);
DriverTorque = output_data.signals.values(:,53);
ExtControlMode = output_data.signals.values(:,54);
MotorTorque = output_data.signals.values(:,55);
TransCurrentGear = output_data.signals.values(:,56);
TransSelectedGear = output_data.signals.values(:,57);


Results_Names={'Time', ...
               'ParkingBrakeSwitch', ...
               'TransmissionNeutralSwitch', ...
               'Door_LH_State', ...
               'Door_RH_State', ...
               'Seatbelt', ...
               'C_AccDisSetSw', ...
               'C_CcPtoEnableSW', ...
               'C_CcRes_Dec_SW', ...
               'C_CcSet_Inc_SW', ...
               'C_LFA_Sw', ...
               'C_Pause_Sw', ...
               'BrakePedalPos', ...
               'BrkPrssHghRngFrntLftWheel', ...
               'BrkPrssHghRngFrntRghtWheel', ...
               'BrkPrssHghRngRrLftWheel', ...
               'BrkPrssHghRngRrRghtWheel', ...
               'FrontAxleLeftWheelSpeed', ...
               'FrontAxleRightWheelSpeed', ...
               'RearAxleLeftWheelSpeed', ...
               'RearAxleRightWheelSpeed', ...
               'LateralAcceleration', ...
               'LongitudinalAcceleration', ...
               'SteerWheelAngle', ...
               'YawRate', ...
               'BrakeSwitch', ...
               'ParkingBrakeSwitch', ...
               'SteeringAngle', ...
               'SteeringAngleSpeed', ...
               'DriverTorque', ...
               'ExtControlMode', ...
               'MotorTorque', ...
               'TransCurrentGear', ...
               'TransSelectedGear'};
           
Results_Values=[Time,ParkingBrakeSwitch, ...
                TransmissionNeutralSwitch, ...
                Door_LH_State, ...
                Door_RH_State, ...
                Seatbelt, ...
                C_AccDisSetSw, ...
                C_CcPtoEnableSW, ...
                C_CcRes_Dec_SW, ...
                C_CcSet_Inc_SW, ...
                C_LFA_Sw, ...
                C_Pause_Sw, ...
                BrakePedalPos, ...
                BrkPrssHghRngFrntLftWheel, ...
                BrkPrssHghRngFrntRghtWheel, ...
                BrkPrssHghRngRrLftWheel, ...
                BrkPrssHghRngRrRghtWheel, ...
                FrontAxleLeftWheelSpeed, ...
                FrontAxleRightWheelSpeed, ...
                RearAxleLeftWheelSpeed, ...
                RearAxleRightWheelSpeed, ...
                LateralAcceleration, ...
                LongitudinalAcceleration, ...
                SteerWheelAngle, ...
                YawRate, ...
                BrakeSwitch, ...
                MFSMmsg02_ParkingBrakeSwitch, ...
                SteeringAngle, ...
                SteeringAngleSpeed, ...
                DriverTorque, ...
                ExtControlMode, ...
                MotorTorque, ...
                TransCurrentGear, ...
                TransSelectedGear];

sheet=2;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=2;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% GENERAL INFO 
Time = output_data.time(:,1);
Day_Time_Indicator = output_data.signals.values(:,58);
LaneModuleValid = output_data.signals.values(:,59);
MpoTrack_ID = output_data.signals.values(:,60);
Road_Type = output_data.signals.values(:,61);
Sensor_State = output_data.signals.values(:,62);

Results_Names={'Time','Day_Time_Indicator','LaneModuleValid','MpoTrack_ID','Road_Type','Sensor_State'};
Results_Values=[Time,Day_Time_Indicator,LaneModuleValid,MpoTrack_ID,Road_Type,Sensor_State];


sheet=3;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=3;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% TRACK_1 
Time = output_data.time(:,1);
Track1_A_Classification_1A = output_data.signals.values(:,63);
Track1_A_Confidence = output_data.signals.values(:,64);
Track1_A_DynState = output_data.signals.values(:,65);
Track1_A_FusionState = output_data.signals.values(:,66);
Track1_TrackId = output_data.signals.values(:,67);
Track1_TrackingState = output_data.signals.values(:,68);
Track1_A_TrackWidth_1A = output_data.signals.values(:,69);
Track1_B_RelAccX_1B = output_data.signals.values(:,70);
Track1_B_RelVelX_1B = output_data.signals.values(:,71);
Track1_B_RelVelY_1B = output_data.signals.values(:,72);
Track1_B_RelAccY_1B = output_data.signals.values(:,73);
Track1_C_RelDistX_1C = output_data.signals.values(:,74);
Track1_C_RelDistY = output_data.signals.values(:,75);

Results_Names={'Time', ...
               'Track1_A_Classification_1A', ...
               'Track1_A_Confidence', ...
               'Track1_A_DynState', ...
               'Track1_A_FusionState', ...
               'Track1_TrackId', ...
               'Track1_TrackingState', ...
               'Track1_A_TrackWidth_1A', ...
               'Track1_B_RelAccX_1B', ...
               'Track1_B_RelVelX_1B', ...
               'Track1_B_RelVelY_1B', ...
               'Track1_B_RelAccY_1B', ...
               'Track1_C_RelDistX_1C', ...
               'Track1_C_RelDistY'};
Results_Values=[Time, ...
                Track1_A_Classification_1A, ...
                Track1_A_Confidence, ...
                Track1_A_DynState, ...
                Track1_A_FusionState, ...
                Track1_TrackId, ...
                Track1_TrackingState, ...
                Track1_A_TrackWidth_1A, ...
                Track1_B_RelAccX_1B, ...
                Track1_B_RelVelX_1B, ...
                Track1_B_RelVelY_1B, ...
                Track1_B_RelAccY_1B, ...
                Track1_C_RelDistX_1C, ...
                Track1_C_RelDistY];

sheet=4;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=4;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% TRACK_2 
Time = output_data.time(:,1);
Track2_A_Classification_2A = output_data.signals.values(:,76);
Track2_A_Confidence = output_data.signals.values(:,77);
Track2_A_DynState = output_data.signals.values(:,78);
Track2_A_FusionState = output_data.signals.values(:,79);
Track2_TrackId = output_data.signals.values(:,80);
Track2_TrackingState = output_data.signals.values(:,81);
Track2_A_TrackWidth_2A = output_data.signals.values(:,82);
Track2_B_RelAccX_2B = output_data.signals.values(:,83);
Track2_B_RelVelX_2B = output_data.signals.values(:,84);
Track2_B_RelVelY_2B = output_data.signals.values(:,85);
Track2_B_RelAccY_2B = output_data.signals.values(:,86);
Track2_C_RelDistX_2C = output_data.signals.values(:,87);
Track2_C_RelDistY = output_data.signals.values(:,88);

Results_Names={'Time', ...
               'Track2_A_Classification_2A', ...
               'Track2_A_Confidence', ...
               'Track2_A_DynState', ...
               'Track2_A_FusionState', ...
               'Track2_TrackId', ...
               'Track2_TrackingState', ...
               'Track2_A_TrackWidth_2A', ...
               'Track2_B_RelAccX_2B', ...
               'Track2_B_RelVelX_2B', ...
               'Track2_B_RelVelY_2B', ...
               'Track2_B_RelAccY_2B', ...
               'Track2_C_RelDistX_2C', ...
               'Track2_C_RelDistY'};
Results_Values=[Time, ...
                Track2_A_Classification_2A, ...
                Track2_A_Confidence, ...
                Track2_A_DynState, ...
                Track2_A_FusionState, ...
                Track2_TrackId, ...
                Track2_TrackingState, ...
                Track2_A_TrackWidth_2A, ...
                Track2_B_RelAccX_2B, ...
                Track2_B_RelVelX_2B, ...
                Track2_B_RelVelY_2B, ...
                Track2_B_RelAccY_2B, ...
                Track2_C_RelDistX_2C, ...
                Track2_C_RelDistY];

sheet=5;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=5;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% TRACK_3 
Time = output_data.time(:,1);
Track3_A_Classification_3A = output_data.signals.values(:,89);
Track3_A_Confidence = output_data.signals.values(:,90);
Track3_A_DynState = output_data.signals.values(:,91);
Track3_A_FusionState = output_data.signals.values(:,92);
Track3_TrackId = output_data.signals.values(:,93);
Track3_TrackingState = output_data.signals.values(:,94);
Track3_A_TrackWidth_3A = output_data.signals.values(:,95);
Track3_B_RelAccX_3B = output_data.signals.values(:,96);
Track3_B_RelVelX_3B = output_data.signals.values(:,97);
Track3_B_RelVelY_3B = output_data.signals.values(:,98);
Track3_B_RelAccY_3B = output_data.signals.values(:,99);
Track3_C_RelDistX_3C = output_data.signals.values(:,100);
Track3_C_RelDistY = output_data.signals.values(:,101);

Results_Names={'Time', ...
               'Track3_A_Classification_3A', ...
               'Track3_A_Confidence', ...
               'Track3_A_DynState', ...
               'Track3_A_FusionState', ...
               'Track3_TrackId', ...
               'Track3_TrackingState', ...
               'Track3_A_TrackWidth_3A', ...
               'Track3_B_RelAccX_3B', ...
               'Track3_B_RelVelX_3B', ...
               'Track3_B_RelVelY_3B', ...
               'Track3_B_RelAccY_3B', ...
               'Track3_C_RelDistX_3C', ...
               'Track3_C_RelDistY'};
Results_Values=[Time, ...
                Track3_A_Classification_3A, ...
                Track3_A_Confidence, ...
                Track3_A_DynState, ...
                Track3_A_FusionState, ...
                Track3_TrackId, ...
                Track3_TrackingState, ...
                Track3_A_TrackWidth_3A, ...
                Track3_B_RelAccX_3B, ...
                Track3_B_RelVelX_3B, ...
                Track3_B_RelVelY_3B, ...
                Track3_B_RelAccY_3B, ...
                Track3_C_RelDistX_3C, ...
                Track3_C_RelDistY];

sheet=6;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=6;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% Track 4 
Time = output_data.time(:,1);
Track4_A_Classification_4A = output_data.signals.values(:,102);
Track4_A_Confidence = output_data.signals.values(:,103);
Track4_A_DynState = output_data.signals.values(:,104);
Track4_A_FusionState = output_data.signals.values(:,105);
Track4_TrackId = output_data.signals.values(:,106);
Track4_TrackingState = output_data.signals.values(:,107);
Track4_A_TrackWidth_4A = output_data.signals.values(:,108);
Track4_B_RelAccX_4B = output_data.signals.values(:,109);
Track4_B_RelVelX_4B = output_data.signals.values(:,110);
Track4_B_RelVelY_4B = output_data.signals.values(:,111);
Track4_B_RelAccY_4B = output_data.signals.values(:,112);
Track4_C_RelDistX_4C = output_data.signals.values(:,113);
Track4_C_RelDistY = output_data.signals.values(:,114);

Results_Names={'Time', ...
               'Track4_A_Classification_4A', ...
               'Track4_A_Confidence', ...
               'Track4_A_DynState', ...
               'Track4_A_FusionState', ...
               'Track4_TrackId', ...
               'Track4_TrackingState', ...
               'Track4_A_TrackWidth_4A', ...
               'Track4_B_RelAccX_4B', ...
               'Track4_B_RelVelX_4B', ...
               'Track4_B_RelVelY_4B', ...
               'Track4_B_RelAccY_4B', ...
               'Track4_C_RelDistX_4C', ...
               'Track4_C_RelDistY'};
Results_Values=[Time, ...
                Track4_A_Classification_4A, ...
                Track4_A_Confidence, ...
                Track4_A_DynState, ...
                Track4_A_FusionState, ...
                Track4_TrackId, ...
                Track4_TrackingState, ...
                Track4_A_TrackWidth_4A, ...
                Track4_B_RelAccX_4B, ...
                Track4_B_RelVelX_4B, ...
                Track4_B_RelVelY_4B, ...
                Track4_B_RelAccY_4B, ...
                Track4_C_RelDistX_4C, ...
                Track4_C_RelDistY];

sheet=7;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=7;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% Track 5 
Time = output_data.time(:,1);
Track5_A_Classification_5A = output_data.signals.values(:,115);
Track5_A_Confidence = output_data.signals.values(:,116);
Track5_A_DynState = output_data.signals.values(:,117);
Track5_A_FusionState = output_data.signals.values(:,118);
Track5_TrackId = output_data.signals.values(:,119);
Track5_TrackingState = output_data.signals.values(:,120);
Track5_A_TrackWidth_5A = output_data.signals.values(:,121);
Track5_B_RelAccX_5B = output_data.signals.values(:,122);
Track5_B_RelVelX_5B = output_data.signals.values(:,123);
Track5_B_RelVelY_5B = output_data.signals.values(:,124);
Track5_B_RelAccY_5B = output_data.signals.values(:,125);
Track5_C_RelDistX_5C = output_data.signals.values(:,126);
Track5_C_RelDistY = output_data.signals.values(:,127);

Results_Names={'Time', ...
               'Track5_A_Classification_5A', ...
               'Track5_A_Confidence', ...
               'Track5_A_DynState', ...
               'Track5_A_FusionState', ...
               'Track5_TrackId', ...
               'Track5_TrackingState', ...
               'Track5_A_TrackWidth_5A', ...
               'Track5_B_RelAccX_5B', ...
               'Track5_B_RelVelX_5B', ...
               'Track5_B_RelVelY_5B', ...
               'Track5_B_RelAccY_5B', ...
               'Track5_C_RelDistX_5C', ...
               'Track5_C_RelDistY'};
Results_Values=[Time, ...
                Track5_A_Classification_5A, ...
                Track5_A_Confidence, ...
                Track5_A_DynState, ...
                Track5_A_FusionState, ...
                Track5_TrackId, ...
                Track5_TrackingState, ...
                Track5_A_TrackWidth_5A, ...
                Track5_B_RelAccX_5B, ...
                Track5_B_RelVelX_5B, ...
                Track5_B_RelVelY_5B, ...
                Track5_B_RelAccY_5B, ...
                Track5_C_RelDistX_5C, ...
                Track5_C_RelDistY];

sheet=8;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=8;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);

% Track 6 
Time = output_data.time(:,1);
Track6_A_Classification_6A = output_data.signals.values(:,128);
Track6_A_Confidence = output_data.signals.values(:,129);
Track6_A_DynState = output_data.signals.values(:,130);
Track6_A_FusionState = output_data.signals.values(:,131);
Track6_TrackId = output_data.signals.values(:,132);
Track6_TrackingState = output_data.signals.values(:,133);
Track6_A_TrackWidth_6A = output_data.signals.values(:,134);
Track6_B_RelAccX_6B = output_data.signals.values(:,135);
Track6_B_RelVelX_6B = output_data.signals.values(:,136);
Track6_B_RelVelY_6B = output_data.signals.values(:,137);
Track6_B_RelAccY_6B = output_data.signals.values(:,138);
Track6_C_RelDistX_6C = output_data.signals.values(:,139);
Track6_C_RelDistY = output_data.signals.values(:,140);

Results_Names={'Time', ...
               'Track6_A_Classification_6A', ...
               'Track6_A_Confidence', ...
               'Track6_A_DynState', ...
               'Track6_A_FusionState', ...
               'Track6_TrackId', ...
               'Track6_TrackingState', ...
               'Track6_A_TrackWidth_6A', ...
               'Track6_B_RelAccX_6B', ...
               'Track6_B_RelVelX_6B', ...
               'Track6_B_RelVelY_6B', ...
               'Track6_B_RelAccY_6B', ...
               'Track6_C_RelDistX_6C', ...
               'Track6_C_RelDistY'};
Results_Values=[Time, ...
                Track6_A_Classification_6A, ...
                Track6_A_Confidence, ...
                Track6_A_DynState, ...
                Track6_A_FusionState, ...
                Track6_TrackId, ...
                Track6_TrackingState, ...
                Track6_A_TrackWidth_6A, ...
                Track6_B_RelAccX_6B, ...
                Track6_B_RelVelX_6B, ...
                Track6_B_RelVelY_6B, ...
                Track6_B_RelAccY_6B, ...
                Track6_C_RelDistX_6C, ...
                Track6_C_RelDistY];

sheet=9;
xlRange='A2';
xlswrite(filename,Results_Values,sheet,xlRange);

sheet=9;
xlRange='A1';
xlswrite(filename,Results_Names,sheet,xlRange);
    
end

